model : 'SVC'
hyper : {
 C :  [0.01 , 0.05 , 0.1 , 0.3 ,0.7 , 1, 5 , 10, 25 ,50 , 75 ,100],
 kernel : ['linear', 'poly', 'rbf', 'sigmoid'],
 degree : [3 , 5 , 9 , 11 , 17 , 21],
 gamma : ['auto','scale'],
 coef0 : [0.0],
 shrinking : [True],
 probability : [False],
 class_weight : [{0: 0.52649733 , 1:  9.93491124} ,
                 {0: 0.52649733 ,1: 18}, 
                 {0: 0.52649733,1: 27}, {0: 1,1: 1}],
 random_state : [666]
 }
 
---
model : 'XGB'
hyper : {
  max_depth : [3,6,10],
  learning_rate : [0.01, 0.05, 0.1],
  n_estimators : [100, 500, 1000],
  #colsample_bytree : [0.3, 0.7],
  #colsample_bylevel : [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
  random_state : [666]
 }
